version: "3"
services:
  chirper-tweet:
    image: hmisonne/udagram-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DATABASE 
      POSTGRES_HOST: $POSTGRES_HOST 
