version: '3'
services:
  udagram-feed:
    build:
      context: ../../chirper-api-tweet
      dockerfile: Dockerfile
    image: hmisonne/chirper-tweet
  reverseproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: hmisonne/reverseproxy