apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirper-tweet
  labels:
    service: chirper-tweet
spec:
  replicas: 1
  selector:
    matchLabels:
      service: chirper-tweet
  template:
    metadata:
      labels:
        service: chirper-tweet
    spec:
      containers:
      - name: chirper-tweet
        image: hmisonne/chirper-tweet:latest
        ports:
          - containerPort: 8080
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL 
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_USERNAME
      restartPolicy: Always