apiVersion: v1
kind: Service
metadata:
  name: chirper-tweet
  labels:
    service: chirper-tweet
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: chirper-tweet